[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  [[images.remote_patterns]]
    protocol = "https"
    hostname = "ext.same-assets.com"

